// Darsh Dental Depot — Complete AI Chatbot Domain Knowledge Base

export const DEPOT_KNOWLEDGE = {
  business: {
    name: "Darsh Dental Depot",
    tagline: "Vadodara's Most Trusted Dental Wholesale & Clinic Supply Depot",
    proprietors: "Hetal Gandhi & Smit Gandhi",
    address: "Bordi Faliya Small Lane, B/h Khanderao Market, Siyabaug / Kevdabaug, Vadodara, Gujarat - 390001",
    landmark: "Vraj Vihar Complex, Char Rasta, Near Khanderao Market",
    phoneNumbers: ["+91-97270 76119", "+91-91577 16989"],
    email: "hetalgandhi16@gmail.com",
    workingHours: "Monday to Saturday: 9:30 AM to 8:30 PM (Sunday by appointment)",
    drugLicense: "DL No. GJ-VAD-215550 & DL No. GJ-VAD-215551",
    gstin: "24ANKPG4381M1ZP",
    pan: "ANKPG4381M",
    state: "Gujarat (Code: 24)",
    bankDetails: {
      bankName: "IDBI BANK BANK LTD",
      accNumber: "0553102000031189",
      branch: "SIDDHANATH Branch, Vadodara",
      ifsc: "IBKL0000553",
    },
  },

  services: {
    sameDayDelivery: "Express same-day clinic delivery across all Vadodara zones (Akshar Chowk, Old Padra Road, Alkapuri, Sayajigunj, Manjalpur, Karelibaug, Gotri, Waghodia Road, Fatehgunj, Sama, Vasna, Subhanpura, Nizampura).",
    paymentModes: [
      "Pay on Delivery (Cash / Clinic Cheque on delivery)",
      "Razorpay Online (UPI, Google Pay, PhonePe, Paytm, Visa, Mastercard, Net Banking)",
    ],
    invoicing: "Official Tally ERP GST Tax Invoices (with HSN codes 90184900, 30064000, 27111300 and 5%/12%/18% tax breakdown) downloadable with 1 click from doctor and shop portals.",
    orderTracking: "Real-time 4-stage tracking: 1. Pending (Received) -> 2. Processing (Packing in Depot) -> 3. Shipped (Out for Delivery) -> 4. Delivered.",
    whatsappAlerts: "Instant 1-click WhatsApp dispatch alerts sent directly to doctor mobile numbers with itemized summary.",
  },

  featuredProducts: [
    {
      id: "mani-burs",
      name: "Mani Diamond Burs (BR-31C, EX-21EF, TR-13, SF-41)",
      brand: "Mani Japan",
      category: "Burs & Rotary",
      hsn: "90184900",
      gstRate: 5,
      price: 300,
      description: "High-grade Japanese multi-use diamond rotary burs for cavity preparation and crown cutting.",
    },
    {
      id: "gc-gold-label-1",
      name: "GC Gold Label 1 (Luting & Lining Cement)",
      brand: "GC Corporation",
      category: "Cements & Liners",
      hsn: "30064000",
      gstRate: 5,
      price: 3169,
      description: "Universal glass ionomer luting cement for crowns, bridges, inlays, and orthodontic bands.",
    },
    {
      id: "gc-fuji-ix",
      name: "GC Fuji IX Extra Posterior Restorative",
      brand: "GC Corporation",
      category: "Restoratives",
      hsn: "30064000",
      gstRate: 5,
      price: 2450,
      description: "High-strength packable glass ionomer restorative cement for posterior restorations and core build-up.",
    },
    {
      id: "tetric-n-ceram",
      name: "Tetric N-Ceram Syringe 4g",
      brand: "Ivoclar Vivadent",
      category: "Composites",
      hsn: "30064000",
      gstRate: 5,
      price: 1250,
      description: "Light-curing, radiopaque nano-hybrid composite for direct restorative procedures (Anterior & Posterior).",
    },
    {
      id: "tetric-n-flow",
      name: "Tetric N-Flow Syringe 2g",
      brand: "Ivoclar Vivadent",
      category: "Composites",
      hsn: "30064000",
      gstRate: 5,
      price: 892.86,
      description: "Flowable nano-hybrid composite with excellent wettability for cavity lining and small restorations.",
    },
    {
      id: "progel-b",
      name: "Progel-B Topical Anesthetic Gel 30g",
      brand: "Prevest DenPro",
      category: "Anesthetics & Surgical",
      hsn: "30039034",
      gstRate: 5,
      price: 447.62,
      description: "Fast-acting 20% benzocaine topical anesthetic gel with pleasant bubblegum/mint flavor.",
    },
    {
      id: "rc-help",
      name: "RC Help 3gm Syringe (EDTA Gel)",
      brand: "Prime Dental",
      category: "Endodontics",
      hsn: "30064000",
      gstRate: 5,
      price: 133.33,
      description: "Water-soluble 17% EDTA gel with carbamide peroxide for root canal lubrication and chelation.",
    },
    {
      id: "gdc-curette",
      name: "GDC Gracey Curette Set",
      brand: "GDC Instruments",
      category: "Instruments",
      hsn: "9018",
      gstRate: 5,
      price: 535,
      description: "Premium surgical stainless steel periodontal subgingival scaling and root planing instruments.",
    },
  ],

  faq: [
    {
      q: "How fast is delivery in Vadodara?",
      a: "Orders placed before 4:00 PM are delivered same-day directly to your clinic via our Kevdabaug depot express dispatch van.",
    },
    {
      q: "Do you provide GST Tax Invoices?",
      a: "Yes! Every single order generated on Darsh Dental Depot creates a Tally ERP compliant GST Tax Invoice with our IDBI Bank credentials, DL numbers, and HSN breakdowns.",
    },
    {
      q: "Can I pay by Cash or UPI on delivery?",
      a: "Yes, we offer Pay on Delivery (Cash on Delivery) as well as online Razorpay payments with instant confirmation.",
    },
    {
      q: "Can I place an urgent order or bulk inquiry via WhatsApp?",
      a: "Absolutely! You can 1-click WhatsApp Hetal Uncle or Smit Gandhi directly on +91 97270 76119.",
    },
  ],
};
